---
image: voegelas/debian-devel

test:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  script:
    - apt-get install -y libmaxminddb-dev pkgconf
    - perl Makefile.PL
    - cover -test
