---
name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: |
          brew install libmaxminddb
      - name: Run tests
        run: |
          perl Makefile.PL
          make test
