---
name: windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    strategy:
      matrix:
        perl: ["5.40", "5.14"]
        distribution: ["default", "strawberry"]
        exclude:
          - distribution: strawberry
            perl: "5.34"
      fail-fast: false
    env:
      MAKECMD: ${{ (matrix.distribution == 'strawberry' && matrix.perl < 5.26 && 'dmake') || 'gmake' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ matrix.distribution }}
          enable-modules-cache: false
      - name: Install dependencies
        run: |
          cpanm https://github.com/voegelas/Alien-libmaxminddb/archive/refs/heads/main.tar.gz
          cpanm --quiet --notest --installdeps .
      - name: Build module
        run: |
          perl Makefile.PL
          ${{ env.MAKECMD }}
      - name: Run tests
        run: |
          ${{ env.MAKECMD }} test
